# syntax = docker/dockerfile:experimental
FROM node:12-alpine

ENV YARN_CACHE_FOLDER=/var/tmp/yarn

RUN apk add --update inotify-tools procps

WORKDIR /srv
COPY lerna.json .
COPY yarn.lock .
COPY package.json .

WORKDIR /srv/utils-number
COPY packages/utils-number/package.json .
COPY packages/utils-number/yarn.lock .
RUN --mount=type=cache,id=yarn-cache,target=/var/tmp/yarn yarn install

WORKDIR /srv/ms-calculation
COPY packages/ms-calculation/package.json .
COPY packages/ms-calculation/yarn.lock .
RUN --mount=type=cache,id=yarn-cache,target=/var/tmp/yarn yarn install
