# syntax = docker/dockerfile:experimental
FROM node:12-alpine

ENV YARN_CACHE_FOLDER=/var/tmp/yarn

RUN apk add --update inotify-tools procps

WORKDIR /srv
COPY lerna.json .
COPY yarn.lock .
COPY package.json .

WORKDIR /srv/api-gateway
COPY packages/api-gateway/package.json .
COPY packages/api-gateway/yarn.lock .
RUN --mount=type=cache,id=yarn-cache,target=/var/tmp/yarn yarn install
