# syntax = docker/dockerfile:experimental
FROM node:12

ENV YARN_CACHE_FOLDER=/var/tmp/yarn

RUN apt-get update && apt-get install inotify-tools make
RUN --mount=type=cache,id=yarn-cache,target=/var/tmp/yarn yarn global add nodemon

WORKDIR /srv
COPY makefile .
COPY lerna.json .
COPY yarn.lock .
COPY package.json .

WORKDIR /srv/packages/api-gateway
COPY packages/api-gateway/package.json .
COPY packages/api-gateway/yarn.lock .

WORKDIR /srv
RUN --mount=type=cache,id=yarn-cache,target=/var/tmp/yarn make install-prod

WORKDIR /srv/packages/api-gateway